global:
  # El remitente smarthost y SMTP utilizado para las notificaciones de correo.
  smtp_smarthost: 'smtp.gmail.com:587'

  smtp_from: 'grafanasugicyt@fundacionsadosky.org.ar'
  smtp_auth_username: 'grafanasugicyt@fundacionsadosky.org.ar'
  smtp_auth_password: '%D5*QrY6eq4*3uU<'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1m
  receiver: 'email'

receivers:

  - name: 'email'
    email_configs:
    - to: 'test@mail.com'
