apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    editable: true

  - name: Desarrollo
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: Testing
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.10.0.78:9090
    basicAuth: false
    isDefault: false
    editable: true

  - name: Preprod
    type: prometheus
    access: proxy
    orgId: 1
    url: http://10.10.0.79:9090
    basicAuth: false
    isDefault: false
    editable: true